# This is a basic workflow to help you get started with Actions

name: Deploy Kripton.Lading to GitHub Pages

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ gh-pages ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  DOTNET_VERSION: 6.0.x

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:      
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v2.1.0
        with:
          # Optional SDK version(s) to use. If not provided, will install global.json version when available. Examples: 2.2.104, 3.1, 3.1.x
          dotnet-version: env.DOTNET_VERSION
      
      - name: Publish Blazor WA project
        run: dotnet publish --project ./Kripton.Landing/*.csproj -c Release -o release --nologo
